spring:
  profiles:
    active: dev2

---
spring:
  application:
    name: eureka-peer
  profiles: dev
server:
  port: 10001

---
spring:
  application:
    name: eureka-peer2
  profiles: dev1
server:
  port: 10002

---
spring:
  application:
    name: eureka-peer3
  profiles: dev2
server:
  port: 10003

---
eureka:
  instance:
    hostname: dev
  client:
    #检索服务
    fetch-registry: false
    #是否将自己注册的eureka
    register-with-eureka: false
    #客户端默认去这个地址去找注册中心
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/,http://localhost:10002/eureka/
  server:
    ### 当eureka启动时，不能从集群节点中获取到instance注册信息，应该等多久
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    ###eureka多长时间更新一次数据
    peer-eureka-nodes-update-interval-ms: 100000
