
server:
  port: 5000
spring:
  application:
    name: configs
  cloud:
    config:
      server:
        git:
          ##定义拉去配置的地址
          uri:
management:
  endpoint:
    web:
      exposure:
        include: "*"

